### ISSUE TITLE
Uncaught ImportError: cannot import name show_message_log


### ISSUE THREAD

**Issue by gubuntu** [boundlessgeo/qgis-what3words#4]
Issue in 2.8 and 2.10. Not an issue in 2.12 and 2.14.

Couldn't load plugin what3words due to an error when calling its classFactory() method
Steps to reproduce
1. First 
2. Second 
3. Third 

```
Traceback (most recent call last):
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/gavin/.qgis2/python/plugins/what3words/__init__.py", line 5, in classFactory
    from plugin import W3WTools
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/what3words/plugin.py", line 13, in <module>
    from processing.core.Processing import Processing
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/__init__.py", line 29, in <module>
    from processing.tools.general import *
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/tools/general.py", line 28, in <module>
    from processing.core.Processing import Processing
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/core/Processing.py", line 46, in <module>
    from processing.modeler.ModelerAlgorithmProvider import ModelerAlgorithmProvider
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/modeler/ModelerAlgorithmProvider.py", line 42, in <module>
    from processing.gui.GetScriptsAndModels import GetModelsAction
  File "/usr/local/qgis-2.8/share/qgis/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/processing/gui/GetScriptsAndModels.py", line 38, in <module>
    from qgis.utils import iface, show_message_log
ImportError: cannot import name show_message_log

```

what3words 1.0, QGIS 2.8.9-Wien on Linux 4.4.0-22-generic

**Comment by alexbruy** [comment]
Not reproducible with QGIS 2.8.9. Please provide information how to reproduce this issue

**Comment by gubuntu** [comment]
Just open QGIS :-) I'm getting this with 2.8.9 26c3ece locally built on Ubuntu Xenial and 2.10.1  48d9afe but not 2.12, 2.14 or master.

**Comment by alexbruy** [comment]
Not reproducible on Windows and Linux. Please check that you have no Processing plugin installed in your user directory

**Comment by gubuntu** [comment]
A-ha, that's the issue, I have Processing installed but see it's not enabled in 2.8 or 2.10 because 

> This plugin is incompatible with this version of QGIS
> Plugin designed for QGIS 2.12 - 2.99

Surely all plugins (especially Processing) should not break with any version of 2? I've created https://hub.qgis.org/issues/14993
